### ISSUE TITLE
FeatureProposal: Support Java8 Completionstage in API

### ISSUE THREAD

**Issue by tkruse** [awaitility/awaitility#100]
I assume Awaitility is often used in conjunction with Java8 CompletionStage. It would be nice if there was a more writable way to await for completion of those, such as:

    CompletionStage<String> stage = CompletableFuture.completedFuture("foo");
    // current
    await().until(() -> stage.toCompletableFuture().isDone());
    // wish to have
    await().untilDone(stage);

**Comment by johanhaleby** [comment]
Sounds like a nice addition but the problem is that Awaitility is built to work on Java 6 :/ So I don't think there's a way to work-around that?

**Comment by johanhaleby** [comment]
Also can't you just use `join` on the `CompletableFuture` instead of using awaitility?

**Comment by tkruse** [comment]
ok, must be left to the future, then, or an assertj-java8 adapter.
get()/join() is a workaround, not a solution.

**Comment by johanhaleby** [comment]
@tkruse  The next version of Awaitility will require Java 8 so I'm revisting old issues. Is this something that you still would find valuable? If so could you please explain why 

```java
await().untilDone(stage);
```

is better than:

```java
 stage.toCompletableFuture().get(10, TimeUnit.SECONDS);
```

**Comment by tkruse** [comment]
I am not sure. It's been too long since I wrote this kind of code. SO feel free to close, I can reopen if I remember.
