### ISSUE TITLE
Update objenesis to 2.6.0

### ISSUE THREAD

**Issue by Aloren** [awaitility/awaitility#104]
Currently used version is 2.5.1. Can be upgraded to latest: 2.6.0.
[objenesis in maven repo](https://mvnrepository.com/artifact/org.objenesis/objenesis)

**Comment by johanhaleby** [comment]
Does it still work on Java 6?

**Comment by Aloren** [comment]
I suppose yes. According to [release notes](http://objenesis.org/notes.html) in 2.6.0 they dropped support for java 1.5, so I guess 1.6 should still work.

**Comment by johanhaleby** [comment]
Ok, I've now updated the dependency and published a new snapshot. Please try version `3.0.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```
