### ISSUE TITLE
(add option to) simplify condition error messages

### ISSUE THREAD

**Issue by thetoothpick** [awaitility/awaitility#108]
When passing a Java 8 lambda function into ConditionFactory.until() or ConditionFactory.untilAsserted(), the error message that gets generated on failure is very verbose.  For lambda functions, it generates a description of the function including containing class, as well as the types of all variables used from the parent scope.

For example, the following is the error message generated by one of my conditions:

>Condition with alias 'my helpful condition description' didn't complete within 500 milliseconds because assertion condition with alias my helpful condition description defined as a lambda expression in my.long.package.name.MyClass that uses java.util.function.Supplier, java.util.function.Supplierjava.util.Map, java.util.Mapmy.long.package.name.MyOtherClass [my helpful assertion description] `<AssertJ error message>`

First, the alias is repeated twice.  Second, the lambda description is not helpful, since there's already an alias and it's overly verbose.

The message basically boils down to

>Condition with alias '`<alias>`' didn't complete within `<timeout>` because assertion condition with alias `<alias>` defined as `<description>` [`<AssertJ alias>`] `<AssertJ error message>`

I think you can safely remove the second alias portion, and remove the "defined as ..." portion if an alias is defined.  Or make an option to do that and allow it to be set globally (using a static setDefault method in Awaitility).

P.S. there seems to be a hanging "because" in the message that doesn't end up making a full sentence.

**Comment by johanhaleby** [comment]
Is this easily doable? I.e. we don't need to dig into Hamcrest an change the way it generates error messages? If so perhaps you'd like to help out and submit a PR? Hopefully I'm about to release a new version by the end of this week.

**Comment by thetoothpick** [comment]
Unfortunately I need to check with some people to see if I'm allowed to send a PR for this.

I've looked over the code and it seems easy enough.  All the relevant code is in this project.  In `org/awaitility/core/AssertionCondition.java` and `org/awaitility/core/CallableCondition.java`, the method `generateDescriptionPrefix()` generates the second "alias" string and the "description" sting.  There's already an if statement for when the method is a lambda, and an if statement for the presence of an alias.  That could easily be changed to not add the lambda description if there is an alias (in `if (hasAlias) {}`, just return the string without the "defined as a" portion).

The double alias display is an unfortunate side effect of the prefix generator method being used for two purposes, the `getTimeoutMessage()` function from `ConditionAwaiter` and the `conditionEvaluationHandler.handleConditionResult<Match/Mismatch>()` calls.  The first adds the alias already, the second does not.  So there isn't a super easy fix to that without some restructuring required.

The Hamcrest condition classes don't seem to be affected by this problem, because they don't describe the matcher, so those shouldn't need to be touched.

If I can send a PR I will, but it amounts to a 10-line change across 2 files (assuming the change is to the default behavior and an option isn't being used).  If I'm not able to send a PR and you have time to make the change, it would be much appreciated.

Thanks!

**Comment by johanhaleby** [comment]
I've fixed this in master now

**Comment by thetoothpick** [comment]
Thanks for the change!

I was more concerned about the long lambda description than the second alias, though.  Would it be possible to add the ability to remove that lambda description from the message in a future release?

Thanks!
