### ISSUE TITLE
Should the awaitility be used for only test code? 

### ISSUE THREAD

**Issue by juhwany** [awaitility/awaitility#110]
This is not issue, it's just question.

I'm considering using this awesome library in general business code in my project.
For example, for long period job this library is very useful for checking whether the job is done.

But it seems like that this library is only for test code such as unit test. Because the guide documents says "Testing asynchronous systems is hard. Not only does it require handling threads, timeouts and concurrency issues, but the intent of the test code can be obscured by all these details" 
And it guides to add dependency library as test scope like the below.
<dependency>
	<groupId>org.awaitility</groupId>
	<artifactId>awaitility-proxy</artifactId>
	<version>3.1.0</version>
	<scope>test</scope>
</dependency> 

So I'm not sure that this library could be used for general business code.
Should the awaitility be used for only test code?

**Comment by johanhaleby** [comment]
Hi! Thanks for using Awaitility. 

I wouldn't recommend using Awaitility in production as a first choice. The main reason is that there are typically better ways to "wait for something" in a production system which doesn't involve blocking. For example event driven architecture, promises, fibers, coroutines etc.

**Comment by dhet** [comment]
Also note:
* Awaitility comes with transitive test dependencies that you wouldn't want in a production artifact (like JUnit)
* Awaitility's interrupt handling is fine for testing purposes but might lead to unexpected behavior in production (sneaky throwing `InterruptedException`s is not something you would expect from a library)
