### ISSUE TITLE
How to control the frequency of the wait condition execution

### ISSUE THREAD

**Issue by Artgit** [awaitility/awaitility#113]
I use the following wait condition:

`await().atMost(60, SECONDS).until(() -> messageRepository.findAll().size() == 1);`

How frequently this code will execute the ` messageRepository.findAll().size() == 1` condition during the wait phase ?

Is there a possibility to control the frequency of the wait condition execution, let's say check for ` messageRepository.findAll().size() == 1` once per second ? Thanks!

**Comment by szpak** [comment]
Yes, it is. Please check the [user guide](https://github.com/awaitility/awaitility/wiki/Usage#polling).
