### ISSUE TITLE
Awaitility untilTrue condition with the given timeout does not work

### ISSUE THREAD

**Issue by sandraj-cuelogic** [awaitility/awaitility#116]
Awaitility untilTrue condition with the given timeout does not work, the condition gets fulfilled but the execution does not continue. 

I am using await(90, Timeunit.SECONDS).untilTrue(atomic boolean condition)

**Comment by johanhaleby** [comment]
It shouldn't continue if the condition is fulfilled. That's the purpose of Awaitility. What is it that you want to achieve?
