### ISSUE TITLE
ConditionTimeoutException thrown when using ignoreExceptions could expose last thrown exception

### ISSUE THREAD

**Issue by BrynCooke** [awaitility/awaitility#121]
When using `ignoreExceptions()` we get a `ConditionTimeoutException`

```java
await().atMost(ONE_MINUTE)
           .ignoreExceptions()
           .pollDelay(ZERO)
           .pollInterval(ONE_SECOND).until(() ->.......
```

However, it doesn't include any information about the exceptions thrown. So all you know is that the operation failed.
It'd be handy for the last exception thrown to be added to the exception hierarchy.

**Comment by johanhaleby** [comment]
Yes that would be nice. Maybe you could have a look at it?
