### ISSUE TITLE
Testing a condition is maintained

### ISSUE THREAD

**Issue by davidbinderRTE** [awaitility/awaitility#124]
Is there a way to test a condition is maintained for at least a given duration. To test condition A is maintained at least 5 seconds I have the following ugly code in my tests:

```
// do something in my test method
try {
    await().atMost(5, TimeUnit.SECONDS).until(this::testConditionA);
    assert false;
}catch (ConditionTimeoutException e){
    //nothing, everything is alright
}
// do something in my test method
```

Is there a better way to do the same thing ? Something I'd like to write would be:

`
await().atMost(5, TimeUnit.SECONDS).check(this::testConditionA);
`

**Comment by johanhaleby** [comment]
@davidbinderRTE This is something I've been thinking about from time to time. Currently there's no good support for it. There `atLeast` built-in but it's not really what you're after. Maybe you could hack something up by creating a `CondtionEvaluationListener` and store the value of each call to it somewhere and then check afterwards if everything was ok. But this is hacky indeed.

**Comment by amiralibazazi** [comment]
+1 for a feature like this. If I have a moment I might work on something for it and raise a PR.

**Comment by artus** [comment]
My team is in need of this functionality too. We solved it in the same way as @davidbinderRTE did, using the `try` on `ConditionTimeoutException` but that's not really the best way to go. 

Is there any update on this?
