### ISSUE TITLE
Android Ui Test Problem

### ISSUE THREAD

**Issue by falkappel** [awaitility/awaitility#125]
When using awaitility in Android Ui Tests there is a crash in the timeout case because the java.beans.Introspector is missing in the Runtime Environment.

There is only one reference in org.awaitility.core.ConditionAwaiter line 126 to "decapitalize" which could be replaced for full functionality with Android Ui Tests

**Comment by johanhaleby** [comment]
I've published the snapshot now. Please try version `3.1.3-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by falkappel** [comment]
3.1.3-SNAPSHOT is working for me. 👍
