### ISSUE TITLE
Is it possible to set custom message for exeption?

### ISSUE THREAD

**Issue by vyarosh** [awaitility/awaitility#135]
real use case from WebDriver fluent wait:
```
new WebDriverWait(webDriver, 10)
                .withMessage("next button is clickable")
                .until(ExpectedConditions.elementToBeClickable(By.xpath("//button[@id='submit']")));
```
which after 10 second of waiting will provide Exception:
`org.openqa.selenium.TimeoutException: Expected condition failed: next button is clickable (tried for 10 second(s) with 500 MILLISECONDS interval)`

How can I create `await()` with custom message?

**Comment by johanhaleby** [comment]
@vyarosh This is not the Selenium project, this is Awaitility, so I cannot speak for Selenium.

**Comment by vyarosh** [comment]
@johanhaleby I'm asking about **Awaitility** functioanal actually. Selenium was only example of the functional that I would like to have in **Awaitility**.

**Comment by johanhaleby** [comment]
Oh sorry, maybe you can use [aliases](https://github.com/awaitility/awaitility/wiki/Usage#example-6---advanced) or [describedAs](http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/core/DescribedAs.html#describedAs(java.lang.String,%20org.hamcrest.Matcher,%20java.lang.Object...)) on the hamcrest matcher.

**Comment by vyarosh** [comment]
Great! thanks a lot!
