### ISSUE TITLE
Please bump hamcrest versions

### ISSUE THREAD

**Issue by fil512** [awaitility/awaitility#137]
You mentioned you were hoping to do this in version 4 but It looks like it hasn't happened in 4.0.0-rc1

Thanks!
Ken

**Comment by johanhaleby** [comment]
Hmm it should have been updated to 2.1 from 1.3. See [here](https://github.com/awaitility/awaitility/blob/master/pom.xml#L78). However JUnit 4.x depends on hamcrest-core 1.3. Maybe that's whay you're seeing?
