### ISSUE TITLE
Dependency in Getting Started Wiki for Gradle in an Android context

### ISSUE THREAD

**Issue by PattaFeuFeu** [awaitility/awaitility#139]
The [Getting Started](https://github.com/awaitility/awaitility/wiki/Getting_started) guide for Gradle still contains the old `compile` version which has been deprecated in favour of `implementation` and `api` for a while, at least in regards to Android.

Specifically, when using UI tests in Android with a Gradle version that came out after 2017 it should read

`androidTestImplementation 'org.awaitility:awaitility:4.0.0'`

instead of

`testCompile 'org.awaitility:awaitility:4.0.0'`

**Comment by johanhaleby** [comment]
@PattaFeuFeu Oh I actually didn't know this, I'm mainly using Maven nowadays. 

I don't like to change it to `androidTestImplementation` since that sounds very much like an android specific thing. Are you sure that `testCompile` has been superseded by something else? Where can I read up on this?

**Comment by johanhaleby** [comment]
I'm reading [here](https://stackoverflow.com/a/44493379/398441) that `compile` should be replaced with `implementation` and `testCompile` with `testImplementation`. I'm going to update the docs. Thanks for bringing this to my attention.

**Comment by PattaFeuFeu** [comment]
Just the answer I was about to link. :)

The `androidTestImplementation` variant is for (Android) UI tests specifically, while `testImplementation` is for general unit tests.
