### ISSUE TITLE
Condition was evaluated in negative nanoseconds

### ISSUE THREAD

**Issue by minwoox** [awaitility/awaitility#140]
Hello, I recently upgraded the awaitility from `3.1.6` to `4.0.0`.
I saw this weird `ConditionTimeoutException` while compiling using Appveyor:
```
org.awaitility.core.ConditionTimeoutException:
Condition was evaluated in -1220300 nanoseconds which is earlier than expected minimum timeout 0 nanoseconds
```
https://ci.appveyor.com/project/line/armeria/builds/27223324

The build is fine with Travis CI which uses Linux, but not ok with the Appveyor which uses Window OS.

Please let me know if there's something that I missed. 🙇

**Comment by johanhaleby** [comment]
@minwoox This has (hopefully) already been fixed in master (see https://github.com/awaitility/awaitility/pull/138). 

Could you please try version `4.0.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

and see if it fixes the issue? That would be really helpful. If it works I can make a new release today.

**Comment by minwoox** [comment]
Ah yes, let me try that. I will tell you how it works. Thanks!

**Comment by minwoox** [comment]
@johanhaleby I tried it [here](https://github.com/line/armeria/pull/2051) and it worked.

**Comment by johanhaleby** [comment]
@minwoox Great! I'll try to make a new release soon.

**Comment by johanhaleby** [comment]
Awaitility 4.0.1 is now released. It should be available in Maven central shortly (if not already :))

**Comment by minwoox** [comment]
Thanks a lot for your help!
