### ISSUE TITLE
Awaitility hiding exceptions on the same thread

### ISSUE THREAD

**Issue by pelletier2017** [awaitility/awaitility#152]
This is a small program that demonstrates the behavior I'm seeing that appears to be a bug.

Actual behavior:
When this runs it exits and prints IllegalArgumentException stack trace like a normal java program. The weird behavior is if you comment out the line `.dontCatchUncaughtExceptions()`, it will exit with status code 1 and not print the exception.

Expected behavior:
I would expect awaitility to not affect exceptions thrown in the same thread and outside its until() {} block.

Version:
<groupId>org.awaitility</groupId>
<artifactId>awaitility</artifactId>
<version>3.1.2</version>

```java
public static void main(final String... args) throws Exception {
        final AtomicInteger count = new AtomicInteger(0);
        await()
                .dontCatchUncaughtExceptions()
                .ignoreExceptionsMatching(instanceOf(IOException.class))
                .atMost(3, TimeUnit.MINUTES)
                .until(() -> {
                    count.incrementAndGet();
                    return count.get() > 3;
                });

        if (true) {
            System.out.println("throwing an exception");
            throw new IllegalArgumentException("broken");
        }
        System.out.println("Already exited so you won't see this");
}
```

**Comment by grofoli** [comment]
For me it looks like the UncaughtExceptionHandler is set globally and is not reset after condition evaluation. 
@johanhaleby Maybe we can reset the defaultUncaughtException handler to null in the following finally block: https://github.com/awaitility/awaitility/blob/master/awaitility/src/main/java/org/awaitility/core/ConditionAwaiter.java#L170 WDYT? Is this a good approach?

**Comment by johanhaleby** [comment]
Thanks for the report and for your investigation Oliver. It's true that the
UncaughtExceptionHandler is set globally, I don't know of any other way to
catch exceptions from all threads. But I don't really understand what you
mean by "maybe we can reset the defaultUncaughtException handler to null"?

mån 16 dec. 2019 kl. 21:44 skrev Oliver Grof <notifications@github.com>:

**Comment by grofoli** [comment]
I was wondering if it makes sense to add the following line in the mentioned finally block
`Thread.setDefaultUncaughtExceptionHandler(null);`

Another improvement could be to remember the orginalDefaultUncaughtExceptionHandler and set it back like `Thread.setDefaultUncaughtExceptionHandler(orginalDefaultUncaughtExceptionHandler );`. However, I think we are fine with implementing the first option, and set the handler to null.

WDYT, does it makes sense? Or do I miss something?

**Comment by johanhaleby** [comment]
Thanks again for your feedback Oliver.

What would be the drawback of setting it back to the original
"DefaultUncaughtExceptionHandler"? I'm thinking that maybe this would be
better (although a bit more complex) since maybe Awaitility is used in an
environment where a framework sets a DefaultUncaughtExceptionHandler and
maybe Awaitility would be a better citizen if it re-applied the previous
DefaultUncaughtExceptionHandler? WDYT?

**Comment by grofoli** [comment]
IMHO there is no drawback. Actually, I had similar things in mind like you, when I suggested to set back the original DefaultUncaughtExceptionHandler.

**Comment by grofoli** [comment]
I opened a PR few minutes ago. Please be aware that writing a unit test similar to the main method below is not easily possible, because the JUnit Framework has an own Exception handling. Therefore I decided to test an implementation detail in the unit test, namely the reset of the original defaultUncaughtExceptionHandler. 

The following main method throws an IllegalArgumentException exception, which proves that the Awaitility does NOT hide exception on the main thread anymore.

```
public static void main(final String... args) throws Exception {
        final AtomicInteger count = new AtomicInteger(0);
        await()
                .until(() -> {
                    count.incrementAndGet();
                    return count.get() > 3;
                });

        if (true) {
            throw new IllegalArgumentException("broken");
        }
    } 
```

**Comment by johanhaleby** [comment]
@grofoli  thanks a lot for your help again. I've published a new snapshot now if you want to try it out. Please try version `4.0.2-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by grofoli** [comment]
@johanhaleby Great! I will probably try this new snapshot tomorrow (Jan 2, 2020)

**Comment by grofoli** [comment]
@johanhaleby I tried a little bit some simple usages of the libary today and they were working fine. When do you plan to release it? FYI: There is a PR open that I reviewed and suggested a minor change for @metatype. Do you want to include that in the next version as well or do you want to release the current 4.0.2-SNAPSHOT? 
https://github.com/awaitility/awaitility/pull/153

**Comment by johanhaleby** [comment]
Thanks for trying it out, reviewing and reminding me Oliver! :) I'll try
release 4.0.2 now. I can't thank you enough for your efforts on this
release!
