### ISSUE TITLE
Assert blocking call returns in given time

### ISSUE THREAD

**Issue by jeschkies** [awaitility/awaitility#162]
Hi 👋 

I have a test with a blocking call that I would like to time out. JUnit 5 has a `Timeout` annotation coming up. However, I feel it would be easier to debug if one would put a timeout on specific call:

```java
final Int iter = 42

final Int result = await().within(10, SECONDS).until(() -> fibonacci(iter))
```

Would that make sense for Awaitility? This is not about polling but rather putting a max on the time we want to wait.

**Comment by johanhaleby** [comment]
Hi, 

Not sure if I understand. You would like the call to `fibonacci` to timeout? Or are you saying that `fibonacci(iter)` most be completed within 10 seconds otherwise Awaitility should fail the test?

**Comment by jeschkies** [comment]
> `fibonacci(iter)` most be completed within 10 seconds otherwise Awaitility should fail the test?

Yes, it should fail if it does not complete within the timeout. I just found that the latest JUnit 5 release has `@Timeout` and `assertTimeout`. So it might not be suitable for Awaitility.

**Comment by johanhaleby** [comment]
Maybe you could also set a long poll duration and just use `atMost`. Maybe something like this would work:

 ```java
final Int result = await().with().pollInterval(Duration.of(20, SECONDS)).atMost(10, SECONDS).until(() -> fibonacci(iter))
```

But it's probably better to use the built-in timeout properties of the testing library. I'll close this issue for now.

**Comment by jeschkies** [comment]
Thanks for the quick help!
