### ISSUE TITLE
Feature Request: support assertions in failFast condition

### ISSUE THREAD

**Issue by SebastianGoeb** [awaitility/awaitility#238]
The introduction of `untilAsserted()` was great, because intermediate states that don't cause outright failure can be logged with `.conditionEvaluationListener()`, eventual failures are obviously reported as well, but `failFast()` conditions still only have access to a `Predicate`, which comes out as `Fail fast condition triggered` (not very informative), and optionally a hardcoded `String` error message, which is better, but still tells me nothing about the actual problem.

It would be great if `failFast()` could be overloaded to accept an assertion lambda as well, which would then report the assertion message in case of failure, allowing much greater detail in the error message. Another option would be `failFast(Supplier<String> errorMessageSupplier, Callable<Boolean> condition)`, which would also allow me to construct a more detailed failure reason after the fact, when actual failure parameters are known.

In my particular case I am trying to assert that a workflow with many steps completes some number of steps successfully, with a failFast condition if the workflow itself fails. Something along the lines of:
```
await()
    .atMost(1, MINUTES)
    .failFast("workflow failed", this::isWorkflowFailed)
    .untilAsserted(() -> stepShouldBeSuccessful("firstStep"));
await()
    .atMost(1, MINUTES)
    .failFast("workflow failed", this::isWorkflowFailed)
    .untilAsserted(() -> stepShouldBeSuccessful("secondStep"));
...
```
but if the workflow ever does fail, then the `await()` call that was in progress doesn't report the most recent assertion error, only `workflow failed` or `Fail fast condition triggered`, both of which are kinda useless. I'm having to work around this by catching the `TerminalFailureException` and logging the particular failure myself, which I feel should be the responsibility of an assertion.

If I could instead write
```
await()
    .atMost(1, MINUTES)
    .failFast("workflow failed", this::workflowShouldBeRunning)
    .untilAsserted(() -> stepShouldBeSuccessful("firstStep"));
...
void workflowShouldBeRunning() {
    assertThat(workflow.get("phase"))
        .overridingErrorMessage(() -> "Workflow failed. Last known state:\n" + workflow.toPrettyString());
        .isNotEqualTo("Failed");
}
```
that would be great.

**Comment by jhyot** [comment]
I agree that this would be nice. Currently I am "simulating" this by:
```
await()
    .atMost(1, MINUTES)
    .failFast(() -> {
        assertThat(...);
        return false;
      })
    .untilAsserted(() -> <...main assertions...>);
```

**Comment by SebastianGoeb** [comment]
That's a neat idea. I might steal that for myself until this gets implemented. I might even wrap it in a utility method, along the lines of:
```
await()
    .atMost(1, MINUTES)
    .failFast(ifAssertionFails(this::shouldSatisfySomeProperty)
    .untilAsserted(() -> <...main assertions...>);
}
...
static Callable<Boolean> ifAssertionFails(ThrowingRunnable r) {
  try {
    r.run();
    return true;
  } catch (Exception e) {
    LOG.error(e.getMessage(), e);
    return false;
  }
}
```

**Comment by johanhaleby** [comment]
This is a great idea.

**Comment by johanhaleby** [comment]
I have like an hour or so, I'll see what I can do.

**Comment by johanhaleby** [comment]
It should work now!
