### ISSUE TITLE
version 2.0.0 is depend on java 1.7 not 1.6

### ISSUE THREAD

**Issue by wxa56** [awaitility/awaitility#50]
according to Changelog 2.0.0: "Awaitility now requires Java 6"
but "Long.compare(getValueInMS(), other.getValueInMS());" which is used in "Duration.java", is since from java 1.7

**Comment by johanhaleby** [comment]
Oh I didn't know that. Could you provide a pull request?

**Comment by szpak** [comment]
In general, I suggest to take a look at http://www.mojohaus.org/animal-sniffer/ and its Maven plugin. If Awaitility was built with Gradle I could even provide a PR :).

**Comment by johanhaleby** [comment]
Thanks for the tip.

**Comment by johanhaleby** [comment]
I've now deployed a new snapshot that should address this issue. Please try version `2.0.1-SNAPSHOT` after having added the following Maven repository:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```
