### ISSUE TITLE
untilNot feature

### ISSUE THREAD

**Issue by lsliwko** [awaitility/awaitility#51]
Add untilNot( () -> checkIfCrashedError() ) feature

Idea is to wait x sec and throw exception if condition is meet.
Example:

publish(message)
awaits().atMost(5, SECONDS).untilNot( () -> errorQueue.size()==0 )

Awesome project!
Just my 0.02

**Comment by johanhaleby** [comment]
I hear what you're saying but I'm a bit skeptical. The reason is that Awaitility already integrates with Hamcrest matchers which allows you to do:

```java
await().atMost(5, SECONDS).until( () -> errorQueue.size(), not(equalTo(0)) )
```

Which is more composable and does not require an increase of the API.

**Comment by lsliwko** [comment]
That would also do
Thanks!
