### ISSUE TITLE
Upgrade to Hamcrest 2.0

### ISSUE THREAD

**Issue by ben-manes** [awaitility/awaitility#52]
fyi, the current release of Hamcrest is, `org.hamcrest:java-hamcrest:2.0.0.0` (note the coordinate changed). There isn't much that has visibly changed, but helps avoid needing to add exclusions for those who've upgraded.

**Comment by johanhaleby** [comment]
Thanks for the tip. I read in the [changes document](https://github.com/hamcrest/JavaHamcrest/blob/master/CHANGES.txt) that it now uses Java 7. Awaitility is supposed to be used from Java 6 but my tests still pass (I'm using the animal-sniffer-maven-plugin). Not sure if this is a problem?

**Comment by ben-manes** [comment]
It appears they future proofed by taking advantage of the version bump to increase the requirements (like Awaitility did with moving off Java 5). But you're right and I missed that conflict.

**Comment by johanhaleby** [comment]
Ok, I guess we'll close this for now. Please tell me if you think otherwise.
