### ISSUE TITLE
add capability to wait until notify invoked, something like untilNotify

### ISSUE THREAD

**Issue by heenenee** [awaitility/awaitility#54]
It might be nice if there was .untilNotify(Object obj) that waited until notify was invoked on the obj argument.

The reason for this is that I have a legacy application that is already significantly relying upon wait/notify, and there are various usages of wait could be simplified to something like `await().atMost(ONE_SECOND).untilNotify(myObj)` without forcing me to refactor all of the existing synchronization logic.

**Comment by johanhaleby** [comment]
Interesting proposal but how would Awaitility find out if notify was called?

**Comment by heenenee** [comment]
Hmm, I didn't think this request through, and how it would fit in with what I'm trying to do...  never mind this for now,  Thanks for responding though!
