### ISSUE TITLE
CGLib dependency should be shaded

### ISSUE THREAD

**Issue by aiannucci** [awaitility/awaitility#55]
CGLib can be specially troublesome when you have different versions of the library that are being pulled by different libraries.
It seems it's a common practice to shade this library (see Spring, Mockito) in order to avoid these problems.
Can you consider this?
Also, the version being used is almost 3 years old, it would be good to upgrade it (latest at this moment is 3.2.4)

**Comment by johanhaleby** [comment]
Sure, sounds like a good idea. Could you perhaps help out with this?

**Comment by johanhaleby** [comment]
The only thing that concerns me about this is the increased dependency size. How large is cglib?

**Comment by aiannucci** [comment]
CGLib is ~300K. If you think this is a concern, another approach is to create an `awaitility-all` package, which can include the shaded CGLib and potentially other libraries, leaving the core dependency as is. Similar to `mockito-core` and `mockito-all`

**Comment by szpak** [comment]
mockito-core and mockito-all are not the best recommendation. It was very confusing for the users and in the end we don't have mockito-all package anymore.

**Comment by johanhaleby** [comment]
@aiannucci Thanks for the info

**Comment by johanhaleby** [comment]
@szpak Thanks for your input. Then I'd say that we just keep it as it is now without splitting up the project into multiple dependencies.
