### ISSUE TITLE
Create bundles for awaitility

### ISSUE THREAD

**Issue by cschneider** [awaitility/awaitility#59]
I would like to use awaitility in pax exam for doing OSGi testing. This requires the jar to be a bundle though. I can provide the needed changes if you are interested.

**Comment by johanhaleby** [comment]
Does that still mean just adding metadata in the manifest file or is there something else that needs to change? It would be great if you could help out with this.

**Comment by cschneider** [comment]
I plan to add the meta data and also an integration test using pax exam. Ideally we will not need anything special but I can only tell after actually testing it in OSGi.

**Comment by johanhaleby** [comment]
It's worth a shot
