### ISSUE TITLE
andThen support after condition has been evaluated?

### ISSUE THREAD

**Issue by pbromley** [awaitility/awaitility#68]
Apologies if I'm coming at this from the wrong angle but is there any support (or direction of how i should do this) for running some code after the condition has been evaluated to true e.g. my current code is as follows

`await().atMost(5, SECONDS).until(() -> someList.size(), is(equalTo(1))`

is there any support for something like

`await().atMost(5, SECONDS).until(() -> someList.size(), is(equalTo(1)).andThen(() -> assertThat(someList.get(0), is(equalTo("hello")))`

so I know there is definitely 1 message, now I can do more assertions on the contents of the list

**Comment by johanhaleby** [comment]
Hi, 

Would this be enough?

```java
List<String> someList = await().atMost(5, SECONDS).until(() -> someList, hasSize(1)));
assertThat(someList.get(0), is(equalTo("hello"))
```

/Johan

**Comment by pbromley** [comment]
i thought it might be, but `await()` doesn't seem to block so the assertThat would get evaluated too soon.

I was just about to answer my own question with this

```
await().atMost(5, SECONDS).until(() -> {
    assertThat(someList.size(), is(equalTo(1)));
    assertThat(someList.get(0), is(equalTo("hello")));
})
```

That seems to run `assertThat(someList.size(), is(equalTo(1)))` for at most 5 seconds before moving onto the next line (probably due to an assertionError being thrown)

**Comment by pbromley** [comment]
whoops - you are right - dodgy logic meant the next bit of code ran after the await() blocked but didn't report correctly.

Apologies - close this and ignore me ;)

**Comment by johanhaleby** [comment]
No problem, thanks for using the library :)
