### ISSUE TITLE
Thread left running

### ISSUE THREAD

**Issue by jschneider** [awaitility/awaitility#69]
This simple test case, leaves a thread running:

  @Test
  public void checkThreadsLeft() throws Exception {
    await("asdf").until(() -> true);
  }

Stack trace of the thread that has been left:

Thread[Thread-0,5,main]
	at java.lang.Thread.sleep(Native Method)
	at org.awaitility.core.ConditionAwaiter$1.run(ConditionAwaiter.java:163)
	at java.lang.Thread.run(Thread.java:745)

Is there a way to terminate this thread?

**Comment by jschneider** [comment]
After a little bit of debugging this is what I found out:

In
org.awaitility.core.ConditionAwaiter#await
the executor is shut down and then there is a wait time of 1 sec.
Only after that shutdownNow() is called.


What should/could be done:
- immediately call shutdownNow()
- or at least add awaitTermination() after the call to shutdownNow().

**Comment by johanhaleby** [comment]
Thanks for the investigation and reporting. I've tried sleeping after "shutdownNow", please try if this alleviates the problem by using version `2.0.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by jschneider** [comment]
In version 3.0.0-rc1 the problem still exists:

Thread[awaitility-poll-scheduling,5,main]
	at java.lang.Thread.sleep(Native Method)
	at org.awaitility.core.ConditionAwaiter$1.run(ConditionAwaiter.java:172)
	at java.lang.Thread.run(Thread.java:745)

**Comment by johanhaleby** [comment]
Thanks for trying it out
