### ISSUE TITLE
Request: Allow setting the exception message that is used when timed out

### ISSUE THREAD

**Issue by theotherp** [awaitility/awaitility#79]
We're using Awaitility in integration tests and it would be great if we could supply a more useful failure message. For example instead of "expected not null but was <null> within 10 seconds." we'd like to see "transfer order not set within 10 seconds" or something like that.

**Comment by johanhaleby** [comment]
You can use an await alias, see [this](https://github.com/awaitility/awaitility/wiki/Usage#example-6---advanced) example.

**Comment by theotherp** [comment]
That's what I already do, but it's not the same.

I wrote a helper method that catches the TimeoutException and fails with a given String parameter as message.

**Comment by johanhaleby** [comment]
Ok, could you elaborate what you're missing with aliases?

**Comment by theotherp** [comment]
So sorry, I misunderstood you. I woke way too early today :-/

**Comment by johanhaleby** [comment]
No problem :)
