### ISSUE TITLE
Consider to use AssertJ instead of Hamcrest lib

### ISSUE THREAD

**Issue by mrniko** [awaitility/awaitility#80]
https://joel-costigliola.github.io/assertj/

**Comment by twillouer** [comment]
:+1:

**Comment by szpak** [comment]
@mrniko For internal tests in Awaitility? Or you would like to be able to use AssertJ assertions in your code (something that I [implemented](https://solidsoft.wordpress.com/2014/04/29/using-assertj-and-awaitility-together-thanks-to-java-8-and-lambdas/) in Awaitility 1.6.0 almost 3 years ago)?

**Comment by johanhaleby** [comment]
Yes I also wonder what you mean since it has been supported for quite a while (see [docs](https://github.com/awaitility/awaitility/wiki/Usage#example-8---using-assertj-or-fest-assert)).

One thing that we could consider would be to make the dependency to Hamcrest optional, but it'll require some non-trivial work I think.

**Comment by longtimeago** [comment]
> One thing that we could consider would be to make the dependency to Hamcrest optional

@johanhaleby This would be very-very nice! Many libs depend on hamcrest in a very nasty way. Some of them depends on very old version (1.1) which is not fully compatible with 1.3.
We would like to use Awaitility in production code but hamcrest compile dependency stops us :(

**Comment by johanhaleby** [comment]
Yes Hamcrest is tightly coupled to Awaitility. With a bit of work I think it ought to be possible to remove it from core and perhaps introduce a new library called `awaitility-hamcrest`. But it would not be backward compatible.

**Comment by longtimeago** [comment]
> But it would not be backward compatible.

@johanhaleby Sure, this is expected cost and totally acceptable imo :)
