### ISSUE TITLE
Add Kotlin support

### ISSUE THREAD

**Issue by iggymoran** [awaitility/awaitility#81]
Awaitility already works fine with Kotlin, but there are a few instances where you can't inline calls to `until`.

It would also be nice to be able to use Kotlin idioms such as:

```
Awaitility.await().until {
    x > y
}
```

**Comment by johanhaleby** [comment]
yeah that would be very interesting indeed. Is this something you'd like to help out with?

**Comment by iggymoran** [comment]
Already started ;-)

**Comment by johanhaleby** [comment]
cool :)

**Comment by johanhaleby** [comment]
I've looked into Kotlin support as well and I don't think there's much we can do. The problem is a clash between Runnable and Callable. The only option I see is to rename any of these methods (which I've done in master). The one taking a `Runnable` is now called `untilAsserted`. This means that we don't need an extension module for Kotlin at all.

**Comment by iggymoran** [comment]
I was thinking of creating a specific wrapper on top of `ConditionFactory` that delegates to it.

**Comment by johanhaleby** [comment]
Yeah I tried to do that as well, but I failed to do so (at least using extension methods). If you have any luck it would be great :) I would prefer not to rename the method. 

Btw the 3.0.0-rc1 should be available in maven central soon.

**Comment by iggymoran** [comment]
@johanhaleby I've done a little prototyping, and come up with this:

```
package org.awaitility.kotlin

import org.awaitility.Awaitility
import org.awaitility.core.ConditionFactory

class KAwaitility {

    fun await() : KConditionFactory = Awaitility.await().kt()
}

fun ConditionFactory.kt() : KConditionFactory = KConditionFactory(this)

class KConditionFactory(private val conditionFactory: ConditionFactory) {

    fun until(condition: () -> Boolean) = conditionFactory.until(condition)
}
```

As a general way of having a Kotlin _wrapper_ over Awaitility.

In doing so, I think you'd be able to revert your changes to the `until` function and not break backward compatibility.

Please let me know if this is something worth pursuing. I can gladly flesh it out and add tests.

**Comment by johanhaleby** [comment]
Interesting, I've always assumed that the way to go would be extension functions. I'm a bit hesitant though since I would prefer that we don't introduce a new API.. I'm just curious, do you think people would prefer a "custom" API per language rather than have one consistent API that works from all?

**Comment by iggymoran** [comment]
I think _ideally_ there would only be one API... and the work you did with `untilAsserted` definitely removes all ambiguity for Kotlin.

Having said that, there are quite a few projects already that provide Kotlin-native APIs for existing APIs.

A few examples are:

- [HamKrest](https://github.com/npryce/hamkrest) (Which we could actually use if we were to have a Kotlin-native API)
- [Mockito Kotlin](https://github.com/nhaarman/mockito-kotlin)

Thoughts?

**Comment by johanhaleby** [comment]
I can see benefits of both approaches. Historically though Awaitility have tried to use extension functions for integration and it has worked well in Groovy and Scala (expect for `until(Runnable)`). So I don't know.. I'd really like more people to express an opinion but it is seems futile so far.
