### ISSUE TITLE
Links broken in "Usage" wiki

### ISSUE THREAD

**Issue by thsaravana** [awaitility/awaitility#84]
In the page "https://github.com/awaitility/awaitility/wiki/Usage", under the section [Links and code examples](https://github.com/awaitility/awaitility/wiki/Usage#links-and-code-examples), the links mentioned are broken.

Eg. 
The link mentioned is:
http://github.org/awaitility/blob/master/awaitility/src/test/java/org/awaitility/UsingAtomicTest.java

but it should be:
https://github.com/awaitility/awaitility/blob/master/awaitility/src/test/java/org/awaitility/UsingAtomicTest.java

Kindly update. Unfortunately we can't create Pull request for Github Wiki, or else I would have fixed it myself.

Thanks for a wonderful library.

**Comment by johanhaleby** [comment]
Thanks for point this out and for your kind words, I've fixed the links now.
