### ISSUE TITLE
Initial poll delay

### ISSUE THREAD

**Issue by andreabertagnolli** [awaitility/awaitility#88]
Hi! 
I would like to know if there's a possibility to set an initial delay for polling.

I need to test an async feature that, when invoked, clear some data and then do some stuff.

In that scenario will be useful to set a initial delay before the assertion, otherwise the test will pass because the assertion will verify before the feature clear the data.

now we setted a thread sleep before using awaitility.

Could be an interesting enhancement?

**Comment by johanhaleby** [comment]
Not sure if I misunderstand you but aren't you looking for `pollDelay`?

**Comment by andreabertagnolli** [comment]
nailed! sorry, I missed it ;)
