### ISSUE TITLE
Ignore Exceptions, but log them

### ISSUE THREAD

**Issue by TheNitek** [awaitility/awaitility#92]
I have a few situations where I don't want certain exceptions to interrupt my wait, but for debugging purposes it's quite valuable to have the information that this exception occured. Therefore it would be nice to be able to register a ExceptionListener (or extend the ConditionEvaluationListener) to handle those exceptions.

**Comment by johanhaleby** [comment]
Isn't it possible to combine `given().ignoreException(..)` with a ConditionEvaluationListener?

**Comment by TheNitek** [comment]
I think I got it working by (mis-)using `ignoreExceptionsMatching(...)` with my logging code and `return true`, but it doesn't feel like good solution ...

**Comment by johanhaleby** [comment]
No that's not an optimal solution. But couldn't you use `ignoreException*` for ignoring the exception(s) and an `ConditionEvaluationListener` for logging purposes?

**Comment by TheNitek** [comment]
But I cannot get the Exception information in the Listener, can I?

**Comment by johanhaleby** [comment]
Not atm, but perhaps it would be a good idea to add this? Would that solve your problem?

**Comment by TheNitek** [comment]
Yes, that would be a good solution!

**Comment by grofoli** [comment]
@johanhaleby What do you think about this issue today (after more than two years)? If you think this is still a good a idea/meaningful feature, then I can probably tackle this. What solution would you prefer? Should I introduce a new method in the `ConditionEvaluationListener` like `onException` ?

**Comment by johanhaleby** [comment]
@grofoli That would be really helpful!

**Comment by grofoli** [comment]
@johanhaleby I hope you like the PR.

**Comment by erwinw** [comment]
> @ johanhaleby I hope you like the PR.

Years later, but ... I really appreciate this API change (and the rest of the project!) -- thanks!
