### ISSUE TITLE
Usage of non-monotonic time causes Duration exception

### ISSUE THREAD

**Issue by ben-manes** [awaitility/awaitility#95]
I am unsure how to investigate this, as it has only happened a few times on TravisCI. The error appears to be [thrown](https://github.com/awaitility/awaitility/blob/9f0422b2b8613c8bc3324fe31e6765fc644f9669/awaitility/src/main/java/org/awaitility/Duration.java#L108) in Duration, from scouring dependencies for the string.

In the test suite, Awaitility's timings are only configured in one location as:
```java
Awaitility.with()
    .pollDelay(1, TimeUnit.MILLISECONDS).and()
    .pollInterval(1, TimeUnit.MILLISECONDS);
```

When searching for internal usages, the only candidate that stands out is [ConditionAwaiter#calculateConditionEvaluationDuration](https://github.com/awaitility/awaitility/blob/9f0422b2b8613c8bc3324fe31e6765fc644f9669/awaitility/src/main/java/org/awaitility/core/ConditionAwaiter.java#L200) where pollingStarted passed in as `System.currentTimeMillis() - pollDelay.getValueInMS()` and `currentTimeMillis()` is calculated again for the duration's difference.

Unfortunately `System.currentTimeMillis()` is not strictly monotonic and may appear to run backwards, e.g. when a thread transitions to a different core or an NTP update, and the underlying source may be fairly coarse. Thus, the value between calls can cause a negative calculation on a heavily loaded system. Since millions of tests are being parallelized to run on a TravisCI box, this seems like a plausible scenario. 

```
Gradle suite > Gradle test > com.github.benmanes.caffeine.cache.AsMapTest.compute_nullKey[109]({1022=-1022, 1024=-1024, 1003=-1003, 1009=-1009, 1007=-1007, 1004=-1004, 1001=-1001, 1025=-1025, 1014=-1014, 1005=-1005, 1021=-1021, 1016=-1016, 1008=-1008, 1020=-1020, 1006=-1006, 1010=-1010, 1011=-1011, 1019=-1019, 1018=-1018, 1002=-1002, 1015=-1015, 1012=-1012, 1013=-1013, 1023=-1023, 1017=-1017}, CacheContext{population=PARTIAL, maximumSize=DISABLED, weigher=DEFAULT, expiry=DISABLED, expiryTime=FOREVER, afterAccess=FOREVER, afterWrite=FOREVER, refreshAfterWrite=DISABLED, keyStrength=WEAK, valueStrength=STRONG, compute=ASYNC, loader=NEGATIVE, isAsyncLoading=false, writer=MOCKITO, cacheExecutor=DIRECT, removalListener=REJECTING, initialCapacity=DEFAULT, stats=ENABLED, implementation=Caffeine}) FAILED
    java.lang.AssertionError: AsMapTest#compute_nullKey
        Caused by:
        java.lang.IllegalArgumentException: value must be >= 0, was -243
Gradle suite > Gradle test > com.github.benmanes.caffeine.cache.AsMapTest.compute_error[110]({1019=-1019, 1001=-1001, 1046=-1046, 1018=-1018, 1049=-1049, 1036=-1036, 1040=-1040, 1039=-1039, 1030=-1030, 1007=-1007, 1013=-1013, 1023=-1023, 1045=-1045, 1009=-1009, 1012=-1012, 1034=-1034, 1025=-1025, 1026=-1026, 1010=-1010, 1011=-1011, 1032=-1032, 1004=-1004, 1021=-1021, 1035=-1035, 1024=-1024, 1022=-1022, 1005=-1005, 1033=-1033, 1016=-1016, 1008=-1008, 1047=-1047, 1003=-1003, 1027=-1027, 1029=-1029, 1017=-1017, 1031=-1031, 1048=-1048, 1015=-1015, 1043=-1043, 1050=-1050, 1014=-1014, 1028=-1028, 1006=-1006, 1002=-1002, 1038=-1038, 1044=-1044, 1020=-1020, 1037=-1037, 1041=-1041, 1042=-1042}, CacheContext{population=FULL, maximumSize=DISABLED, weigher=DEFAULT, expiry=DISABLED, expiryTime=FOREVER, afterAccess=FOREVER, afterWrite=FOREVER, refreshAfterWrite=DISABLED, keyStrength=WEAK, valueStrength=STRONG, compute=ASYNC, loader=NEGATIVE, isAsyncLoading=true, writer=MOCKITO, cacheExecutor=DIRECT, removalListener=DEFAULT, initialCapacity=DEFAULT, stats=ENABLED, implementation=Caffeine}) FAILED
    java.lang.AssertionError: AsMapTest#compute_error
        Caused by:
        java.lang.IllegalArgumentException: value must be >= 0, was -251
194904 tests completed, 2 failed
:caffeine:weakKeysAndStrongValuesStatsAsyncCaffeineTest FAILED
```

**Comment by johanhaleby** [comment]
This is something I've not thought about, so thanks for bringing it up. And thanks for the superb issue report, I'm sure you must have spent a lot of time figuring this out, so I'm very grateful for this.

What do you think would be the best approach to solve this? Should we just add some fancier version containing of a statement like this:

```java
private Duration calculateConditionEvaluationDuration(Duration pollDelay, long pollingStarted) {
    return new Duration(Math.max(System.currentTimeMillis() - pollingStarted, 0), MILLISECONDS).minus(pollDelay);
}
```
I say "fancier" here since I believe that you could run into the same issue with the above code if `minus(pollDelay)` gives a negative result. Or should we perhaps allow negative Durations or cap them at 0 if negative? WDYT?

**Comment by ben-manes** [comment]
It was more confusion than time, until it clicked when I realized the usage. I would have made the same oversight.

I'd want to say use nanoTime, but it's unclear if that is stronger. I agree with the precondition as is to disallow bad values in an API. I'd use a minimum, which I think is `pollDelay + 1` rather than zero in your snippet. Hopefully that would fix it, though it is hard to reproduce and be certain.

**Comment by johanhaleby** [comment]
Ok so I've hopefully fixed this now and I've also published the snapshot. Please try version `3.0.1-SNAPSHOT` after having added the following maven repo:

```xml
<repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots />
        </repository>
</repositories>
```

**Comment by ben-manes** [comment]
Since my test suite passes on a subsequent run, it's not testable nor critical. Instead if I don't reopen after your next release, we can guess that it is fixed. I'm in no rush and it is rare, so this is good for now. Thanks!

**Comment by johanhaleby** [comment]
Sure, drop a note when you feel comfortable that it works or if it fails again.
